export default {
  BEGIN_LOADING: 'BEGIN_LOADING',
  STOP_CONTENT_LOADING: 'STOP_CONTENT_LOADING',
  LOGIN_SUCCESS_ADMIN: 'LOGIN_SUCCESS_ADMIN',
  LOGIN_SUCCESS_POLITICIAN: 'LOGIN_SUCCESS_POLITICIAN',
  LOGIN_SUCCESS_CITIZEN: 'LOGIN_SUCCESS_CITIZEN',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  FETCH_OFFICES_SUCCESS: 'FETCH_OFFICES_SUCCESS',
  FETCH_OFFICES_FAILURE: 'FETCH_OFFICES_FAILURE',
};
